- cs/cs.go
- cs/cs_test.go
- dummystore/dummystore.go
- filestore/filestore.go
- store/storetestcases/deletesegment.go
- store/storetestcases/findsegments.go
> Add helper functions to cs package

- store/storetestcases/findsegments.go
- store/storetestcases/getmapids.go
- store/storetestcases/getsegment.go
- store/storetestcases/storetestcases.go
> Add more store benchmarks

- cmd/generate/doc.go
- cmd/generate/main.go
- generator/generator.go
- generator/generator_test.go
- generator/input.go
- generator/input_test.go
- generator/testdata/nodejs/files/LICENSE
- generator/testdata/nodejs/files/README.md
- generator/testdata/nodejs/files/lib/index.js
- generator/testdata/nodejs/files/package.json
- generator/testdata/nodejs/generator.json
- generator/testdata/nodejs/partials/licenses/bsd.md
- generator/testdata/nodejs/partials/licenses/mit.md
- generator/testdata/nodejs_expected/LICENSE
- generator/testdata/nodejs_expected/README.md
- generator/testdata/nodejs_expected/lib/index.js
- generator/testdata/nodejs_expected/package.json
> Add a generator

- generator/generator_test.go
- generator/input.go
> Fix generator blank inputs

- generator/generator.go
- generator/repo/repo.go
- generator/repo/repo_test.go
It allows fetching a generating projects from a Github repository which
contains a collection of generators.
> Add a package to deal with a generator repository

- cli/util.go
> Fix home dir when cross-compiling

- RELEASE_NOTES.md
- cli/cli.go
- cli/generate.go
These changes make it possible to manage different Stratumn
configurations.
* Update release notes
* Execute init script only if project file exists
* Add env variable to specify config path
> Manage Stratumn configuration

- cmd/filetmpop/Docker
- cmd/filetmpop/doc.go
- cmd/filetmpop/main.go
- tendermint/flags.go
- tendermint/tendermint.go
- tmstore/util_test.go
- vendor/github.com/tendermint/tendermint/config/tendermint/config.go
- Produces a single binary
- Removes overhead
> Bundle Tendermint Application with Tendermint Core:

- .vscode/launch.json
- dummystore/dummystore.go
- filestore/filestore.go
- store/store.go
- store/storehttp/storehttp_test.go
- store/storehttp/util.go
- store/storetestcases/findsegments.go
- store/storetestcases/storetestcases.go
- tmpop/tmpop_test.go
- tmstore/tmstore_test.go
Linked to issue stratumn/sdk#168
> Get segments with several mapIds

- generator/repo/repo.go
- generator/repo/repo_test.go
- strat/cmd/cmd.go
- strat/cmd/generate.go
- strat/cmd/generators.go
- strat/cmd/root.go
- strat/cmd/update.go
Add option --generators-use-local-files to search generator templates from a
local directory without git connection
Issue #170
> Generator: Use files from a directory

- tmpop/tmpop.go
Prevents error from being logged in tmpop tests
> tmpop: check if a validation file has been set

- .travis.yml
- Gopkg.lock
- Gopkg.toml
- generator/generator.go
- tendermint/cmd.go
> tendermint: upgrade to version 0.10.4

- tmpop/testdata/rules.json
- tmpop/tmpop_test.go
- tmstore/testdata/rules.json
- tmstore/tmstore_test.go
- validator/root.go
- validator/validator_test.go
> validators: enable multi-process segment validation

- cmd/tmdummy/Docker
- cmd/tmdummy/main.go
> tmdummy: create dummy ABCI application

- store/store.go
- store/store_test.go
- store/storehttp/storehttp_test.go
- store/storehttp/util.go
- store/storetestcases/findsegments.go
- store/storetestcases/storetestcases.go
- store/storetesting/mockadapter_test.go
- tmpop/tmpop_test.go
> store: findSegments with an empty prevLinkHash

- Gopkg.lock
- Gopkg.toml
- cmd/dummyfossilizer/main.go
- cmd/dummystore/main.go
- cmd/filestore/main.go
- cmd/filetmpop/main.go
- cmd/tmdummy/main.go
- cmd/tmstore/main.go
- fossilizer/fossilizerhttp/cmd.go
- fossilizer/fossilizerhttp/fossilizerhttp.go
- jsonhttp/jsonhttp.go
- jsonws/basic.go
- jsonws/bufferedconn.go
- jsonws/hub.go
- store/storehttp/cmd.go
- tendermint/tendermint.go
- tmpop/cmd.go
- tmpop/commit.go
- tmpop/tmpop.go
- tmstore/tmstore.go
- validator/root.go
- validator/schema.go
> sdk: changed sirupsen imports

- Makefile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/sdk/218)
> sdk: always use static flag for docker image build

- Makefile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/sdk/219)
> sdk: fix go build static flag

- cs/cs.go
- cs/cs_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/sdk/222)
> cs: Enhance unit test coverage

- Gopkg.lock
- Gopkg.toml
- tmpop/dbadapter.go
- tmstore/tmstore.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/sdk/232)
> tendermint: upgrade to version 0.12.0

- bufferedbatch/batch_test.go
- store/store.go
- store/store_test.go
- store/storetestcases/batch.go
- store/storetestcases/findsegments.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/sdk/230)
> storetestcases: add default pagination limit

- CHANGE_LOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/sdk/229)
> release: update CHANGELOG

- Gopkg.lock
- bufferedbatch/batch_test.go
- cs/cs.go
- cs/cs_test.go
- cs/cstesting/cstesting.go
- store/storetestcases/batch.go
- store/storetestcases/findsegments.go
- store/storetestcases/getmapids.go
- tmpop/tmpop_test.go
resolves #189
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/sdk/237)
> canonicaljson: first commit

- bufferedbatch/batch.go
- cs/cs.go
- cs/cs_test.go
- cs/util_test.go
- store/storehttp/storehttp.go
- tmpop/tmpop.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/sdk/220)
> cs: References validation

- store/storetestcases/savesegment.go
- store/storetestcases/storetestcases.go
Try and save a segment whose priority is not set.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/sdk/241)
> storetestcases: add test on priorities

- couchstore/couchstore_test.go
- tmpop/dbadapter.go
- tmpop/tmpoptestcases/lastblock.go
- tmpop/tmpoptestcases/tmpoptestcases.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/sdk/248)
> tmpoptestcases, couchstore: run tmpoptestcases on couchstore

- Gopkg.lock
- couchstore/api.go
- couchstore/couchstore_test.go
- utils/docker.go
I have also improved the create database with a retry to avoid instability in integration testing.
Resolves #244 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/sdk/245)
> couchstore: launch couch container from couchstore test

- cs/cstesting/cstesting.go
- filestore/filestore.go
- filestore/filestore_test.go
- filestore/util_test.go
- store/storetestcases/addevidence.go
- store/storetestcases/addsavechannel.go
- store/storetestcases/createlink.go
- store/storetestcases/findsegments.go
- store/storetestcases/getinfo.go
- store/storetestcases/getmapids.go
- store/storetestcases/getsegment.go
- store/storetestcases/storetestcases.go
Creating a test suite for the updated store interfaces.
I tried to think of a clever way to do it, but I think that in fact it's easier to keep it simple: so I duplicated almost every test and did small changes to make them run against the new interface.
So the resulting PR is quite big, but most of the code is copy-paste (which is bad, but since the goal is to remove completely the code that was copied once the migration is complete, I think it's ok to have that temporary duplication because it's much simpler than complex refactorings).
And in case you are wondering, yeah it was really painful to do :)
https://imgflip.com/i/1zvuwy
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> stores: store v2 test cases

- types/types.go
useful for sql queries with linkHashes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/sdk/257)
> types: implement the value interface on Bytes32

- .vscode/launch.json
- couchstore/api.go
- couchstore/couchstore.go
- couchstore/couchstore_test.go
- couchstore/queries.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/sdk/259)
> couchstore: update to the new store interface

- merkle/dyntree.go
- merkle/merkle.go
- merkle/statictree.go
- merkle/treetestcases/treetestcases.go
I add forgotten last commit from @simonvadee on goprivate.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/sdk/271)
> merkle: small documentation updates

- tmpop/cmd.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/sdk/279)
> tmpop: fix node that does not start

- couchstore/couchstore.go
- dummystore/dummystore.go
- filestore/filestore.go
- postgresstore/postgresstore.go
- rethinkstore/rethinkstore.go
- store/event.go
- store/store.go
- store/store_test.go
- store/storehttp/storehttp.go
- store/storehttp/storehttp_test.go
- store/storetestcases/addsavechannel.go
- tmpop/events.go
- tmpop/tmpop.go
- tmpop/tmpoptestcases/evidence.go
- tmpop/tmpoptestcases/transaction.go
- tmstore/tmstore.go
It's more useful if it allows batching of saved links and maps evidences to a link hash.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/sdk/280)
> store: rework store events

- cs/cs.go
- cs/cs_test.go
- cs/cstesting/cstesting.go
- store/store_test.go
- store/storehttp/storehttp_test.go
- store/storetesting/mockadapter_test.go
Re-add a Validate method on Segment to verify the link hash is correct.
Added a RandomSegment test utility.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/sdk/290)
> cs: validate segment linkhash

- store/storehttp/errors.go
- store/storehttp/storehttp_test.go
- store/storehttp/util.go
Fix #293
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/sdk/294)
> storehttp: parse linkHashes in parseSegmentFilter

- couchstore/queries.go
- cs/cs.go
- postgresstore/reader.go
- rethinkstore/rethinkstore.go
- store/store.go
- store/store_test.go
- store/storehttp/storehttp_test.go
- store/storehttp/util.go
- store/storetestcases/findsegments.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/sdk/295)
> store: SegmentFilter.LinkHashes to []string

- couchstore/couchstore_test.go
- postgresstore/main_test.go
- rethinkstore/main_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/sdk/298)
> ci: fix docker container versions for tests

- couchstore/couchstore.go
- dummystore/dummystore.go
- filestore/filestore.go
- postgresstore/postgresstore.go
- rethinkstore/rethinkstore.go
- store/event.go
- store/store_test.go
- store/storehttp/storehttp_test.go
- tmpop/events.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/sdk/304)
> store: modifiy signature of NewSavedLinks

- strat/cmd/cmd.go
Closes #286
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/sdk/301)
> strat: handle strat commands in stratumn.json when strat is not in PATH

- agent/client/utils_test.go
- batchfossilizer/util_test.go
- bcbatchfossilizer/util_test.go
- blockchain/btc/blockcypher/blockcypher.go
- blockchain/btc/btctesting/btctesting_test.go
- generator/generator.go
- generator/input_test.go
- merkle/statictree_test.go
- store/storetesting/mockadapter_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/sdk/305)
> *: run gofmt -s

- tmstore/tmstore.go
It can be useful for Block Explorers
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/sdk/307)
> tmstore: add LinkHash to tendermint Tx

- bufferedbatch/batch_test.go
- couchstore/couchstore.go
- jsonhttp/jsonhttp.go
- jsonws/basic.go
- postgresstore/reader.go
- tmpop/tmpop.go
- tmpop/tmpoptestcases/query.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/sdk/306)
> Cleanup Go Report issues

- cmd/btcfossilizer/main.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/sdk/313)
> cmd/btcfossilizer: fix typo

- cs/evidence.go
- store/storetestcases/findsegments.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/sdk/315)
> cs: RQL deserialisation of evidences

- rethinkstore/rethinkstore.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/sdk/317)
> rethinkstore: wait for database to be ready at creation

- cmd/couchstore/main.go
Retry until couchdb is ready.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/sdk/318)
> couchstore: add retry to cmd

- .travis.yml
- Makefile
- postgresstore/stmts.go
- test_headers.sh
- validator/validator_test.go
Closes #270
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/sdk/321)
> ci: check that all files have the right license header

- README.md
The gitter automatic PR didn't trigger the build for some reason so it had to be re-pushed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/sdk/325)
> sdk: add gitter badge

- fossilizer/fossilizerhttp/cmd.go
- fossilizer/fossilizerhttp/fossilizerhttp.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/sdk/326)
> fossilizer/fossilizerhttp: remove deprecated option CallbackTimeout

- tmpop/data.go
- tmpop/state.go
- validator/multivalidator.go
- validator/multivalidator_test.go
- validator/validator.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/sdk/330)
> validator: use canonical-json

- Makefile
- agent/agent.go
- agent/agenttestcases/actions.js
- agent/agenttestcases/agenttestcases.go
- agent/agenttestcases/createmap.go
- agent/agenttestcases/createsegment.go
- agent/agenttestcases/findsegments.go
- agent/agenttestcases/getinfo.go
- agent/agenttestcases/getmapids.go
- agent/agenttestcases/getprocess.go
- agent/agenttestcases/getprocesses.go
- agent/agenttestcases/getsegment.go
- agent/agenttestcases/uploadprocess.go
- agent/client/client.go
- agent/client/client_test.go
- agent/client/errors.go
- agent/client/utils_test.go
- agent/plugin.go
- agent/process.go
- bcbatchfossilizer/cmd.go
- blockchain/btc/blockcypher/cmd.go
- blockchain/btc/btctimestamper/cmd.go
- couchstore/queries.go
- tendermint/cmd.go
- test_headers.sh
- tmstore/main_test.go
- tmstore/util_test.go
- utils/signalcontext.go
- utils/signalcontext_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/sdk/331)
> *: fix test_headers script and add missing license headers

- tmpop/tmpoptestcases/evidence.go
- tmpop/tmpoptestcases/query.go
- tmpop/tmpoptestcases/transaction.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-indigocore/346)
> tmpop: prevent unit test crashes

- Makefile
- couchstore/couchstore_test.go
- couchstore/queries.go
- elasticsearchstore/api.go
- elasticsearchstore/elasticsearchstore.go
- elasticsearchstore/elasticsearchstore_test.go
- utils/docker.go
I fixed couple of settings on Semaphore for elastic tests to pass.
I noticed that couch tests are fairly cheap to run as well so I removed the integration flag.
I had to modify the Makefile `LICENSED_FILES` statement in order to not check the ./.semaphore-cache folder (I grep out all the folders starting with a '.')
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-indigocore/360)
> test couch and elastic stores

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-indigocore/363)
> Semaphore badge

- cmd/postgresstore/main.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-indigocore/366)
> add evidence import

- Gopkg.lock
- cs/signature.go
- cs/signature_test.go
- cs/signatures/schemes.go
- cs/signatures/schemes_test.go
This is needed so we can use indigocore `signatures` package in indigotrace.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-indigocore/367)
> signatures, cs: sign messages and links

- validator/governance.go
- validator/governance_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-indigocore/368)
> validator: fix crash on rules deserialization from store

- elasticsearchstore/api.go
- elasticsearchstore/cmd.go
- elasticsearchstore/elasticsearchstore.go
- elasticsearchstore/elasticsearchstore_test.go
- add SimpleSearchQuery
- add MultiMatchQuery (not very useful I think..)
- add specific tests
- add debug logging feature
- handle connection error correctly
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-indigocore/369)
> add search API on Elastic Search store

- tmpop/state.go
- validator/configloader.go
- validator/configloader_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-indigocore/370)
> Small validator fix

- cmd/couchstore/main.go
- cmd/dummystore/main.go
- cmd/dummytmpop/main.go
- cmd/elasticsearchstore/main.go
- cmd/filestore/main.go
- cmd/filetmpop/main.go
- cmd/postgresstore/main.go
- cmd/postgrestmpop/main.go
- cmd/rethinkstore/main.go
- cmd/rethinktmpop/main.go
- cmd/tmstore/main.go
- monitoring/config.go
- monitoring/flags.go
- store/storehttp/cmd.go
- store/storehttp/metrics.go
- tmpop/cmd.go
- tmpop/metrics.go
- tmpop/tmpop.go
Users can configure monitoring parameters via the command-line.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-indigocore/373)
> monitoring: allow custom configuration

- cmd/couchstore/main.go
- cmd/dummystore/main.go
- cmd/elasticsearchstore/main.go
- cmd/filestore/main.go
- cmd/postgresstore/main.go
- cmd/rethinkstore/main.go
- cmd/tmstore/main.go
- couchstore/couchstore.go
- dummystore/dummystore.go
- elasticsearchstore/elasticsearchstore.go
- filestore/filestore.go
- leveldbstore/leveldbstore.go
- monitoring/store.go
- postgresstore/postgresstore.go
- postgresstore/reader.go
- postgresstore/writer.go
- rethinkstore/rethinkstore.go
Thanks @such for the suggestion it's a lot cleaner!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-indigocore/379)
> monitoring: refactor stores to use a monitoring decorator

- Gopkg.lock
- Gopkg.toml
- batchfossilizer/metrics.go
- bufferedbatch/metrics.go
- tmpop/metrics.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-indigocore/382)
> monitoring: update opencensus version

- monitoring/config.go
This small breaking change crept in opencensus and I just noticed it :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-indigocore/383)
> monitoring: fix sampler breaking change

- CHANGE_LOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-indigocore/384)
> changelog: 0.3.0

- cs/cstesting/cstesting.go
- postgresstore/postgresstore_test.go
- rethinkstore/rethinkstore_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-indigocore/385)
> postgresstore, rethinkstore: run tmpop tests

- monitoring/fossilizer.go
Nothing to see here, just approve and move on... ;)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-indigocore/386)
> fossilizer: fix infinite loop

- cmd/elasticsearchstore/main.go
- cmd/rethinkstore/main.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-indigocore/389)
> rethinkstore, elasticsearchstore: add evidence types import

- CHANGE_LOG.md
- Gopkg.lock
- Gopkg.toml
- batchfossilizer/metrics.go
- bufferedbatch/metrics.go
- cs/evidence_tendermint_test.go
- fossilizer/fossilizerhttp/metrics.go
- store/storehttp/metrics.go
- tmpop/metrics.go
- tmpop/tmpoptestcases/evidence.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-indigocore/390)
> tendermint, monitoring: 0.17.1 and fix build

- Gopkg.lock
- Gopkg.toml
- Makefile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-indigocore/393)
> Tendermint 0.18.0

- generator/input.go
- generator/input_test.go
- strat/cmd/generate.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-indigocore/394)
> Sort items lists in CLI

- Dockerfile.tpl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-indigocore/395)
> Dockerfile: update stratumn/gobase version

- CHANGE_LOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-indigocore/396)
> changelog: update tendermint version

- README.md
- RELEASE_NOTES.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-indigocore/397)
> *: rename indigoframework to indigocore

- bufferedbatch/batch_test.go
- cs/cs_test.go
- cs/cstesting/builder.go
- cs/cstesting/cstesting.go
- elasticsearchstore/elasticsearchstore_test.go
- store/storetestcases/batch.go
- store/storetestcases/createlink.go
- store/storetestcases/findsegments.go
- store/storetestcases/getmapids.go
- store/storetestcases/storetestcases.go
- tmpop/tmpoptestcases/evidence.go
- tmpop/tmpoptestcases/query.go
- tmpop/tmpoptestcases/transaction.go
- tmpop/tmpoptestcases/validation.go
- tmstore/tmstore_test.go
- validator/baseconfig_test.go
- validator/governance_test.go
- validator/multivalidator_test.go
- validator/pki_test.go
- validator/schema_test.go
- validator/script_test.go
- validator/transition_test.go
- validator/validator_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-indigocore/407)
> cstesting: add test link builder

- blockchain/btc/blockcypher/cmd.go
- blockchain/btc/btc.go
- blockchain/btc/btc_test.go
I refactored this to use it in alice
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-indigocore/410)
> btc: get bitcoin network ID from WIF

- cs/cstesting/builder.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-indigocore/411)
> cs: add metadata utility in link builder

- fossilizer/fossilizerhttp/fossilizerhttp.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-indigocore/417)
> fossilizer: fix package documentation

- Gopkg.lock
No breaking changes, but let's stay up-to-date
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-indigocore/422)
> monitoring: update opencensus

- cs/cstesting/builder.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-indigocore/430)
> cstesting: action in link builder

- cs/cs.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-indigocore/434)
> cs: add missing json tag

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-indigocore/435)
> ci: install golangci-lint

- Gopkg.lock
- Gopkg.toml
- cs/cs.go
- cs/cs_test.go
- cs/cstesting/cstesting.go
- cs/signature.go
- cs/signature_test.go
- store/storehttp/storehttp_test.go
- tmstore/tmstore_test.go
- validation/configloader.go
- validation/testutils/utils.go
- validation/validators/validator_test.go
https://lesjoiesducode.fr/aprs-8-heures-de-debug
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-indigocore/436)
> upgrade go-crypto

- Gopkg.lock
- postgresstore/postgresstore.go
- postgresstore/reader.go
- postgresstore/stmts.go
- postgresstore/writer.go
Obfuscated links FTW
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-indigocore/439)
> postgres: store protobuf encoded bytes instead of JSON

- Gopkg.lock
- couchstore/couchstore.go
- dummystore/dummystore.go
- elasticsearchstore/elasticsearchstore.go
- filestore/filestore.go
- postgresstore/postgresstore.go
- rethinkstore/rethinkstore.go
- store/storehttp/storehttp.go
- store/storehttp/storehttp_test.go
- store/storetestcases/findsegments.go
- tmpop/state.go
- validation/validators/refs.go
- validation/validators/refs_test.go
Validate prevLinkHash and link references.
Run validations in all stores (this is currently duplicated but I'll do a lot more work on validations refactoring so it will become better).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-indigocore/441)
> chainscript: link validation

- Gopkg.lock
- bufferedbatch/batch.go
- couchstore/couchstore.go
- dummystore/dummystore.go
- elasticsearchstore/elasticsearchstore.go
- filestore/filestore.go
- postgresstore/batch.go
- postgresstore/main_test.go
- postgresstore/postgresstore.go
- postgresstore/postgresstore_test.go
- postgresstore/reader.go
- postgresstore/stmts.go
- postgresstore/tx.go
- postgresstore/writer.go
- rethinkstore/rethinkstore.go
- store/errors.go
- store/storetestcases/createlink.go
- tmstore/tmstore.go
Support for out degree in dummystore, filestore and postrestore.
Other stores return an error when trying to set out degree.
Fixed a few minor issues with postgres.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-indigocore/443)
> stores: support out degree

- couchstore/queries.go
- elasticsearchstore/api.go
- postgresstore/stmts.go
- postgresstore/writer.go
- rethinkstore/rethinkstore.go
- store/store.go
- store/store_test.go
- store/storetestcases/findsegments.go
Support filtering on step.
Will be useful for validations and for applications.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-indigocore/444)
> filters: step

- bcbatchfossilizer/bcbatchfossilizer.go
- blockchain/btc/blockcypher/blockcypher.go
- blockchain/btc/blockcypher/blockcypher_test.go
- blockchain/btc/btc.go
- blockchain/btc/btctesting/btctesting.go
- blockchain/btc/btctesting/btctesting_test.go
- blockchain/btc/btctimestamper/btctimestamper.go
- blockchain/btc/btctimestamper/btctimestamper_test.go
See https://github.com/stratumn/indigostore-api/issues/16
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-indigocore/442)
> blockchain/btc: log remaining balance

- tmpop/state.go
- validation/configloader.go
- validation/configloader_test.go
- validation/filewrapper.go
- validation/metrics.go
- validation/validators/metrics.go
- validation/validators/pki.go
- validation/validators/refs.go
- validation/validators/schema.go
- validation/validators/script.go
- validation/validators/step.go
- validation/validators/transition.go
Adding simple metrics and spans to help monitor validation results.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-core/454)
> validation: add monitoring

- Gopkg.lock
- Gopkg.toml
- batchfossilizer/metrics.go
- bufferedbatch/batch.go
- bufferedbatch/metrics.go
- filestore/batch.go
- fossilizer/fossilizerhttp/fossilizerhttp.go
- monitoring/errorcode.go
- monitoring/fossilizer.go
- monitoring/metrics.go
- monitoring/store.go
- postgresstore/batch.go
- tmpop/metrics.go
- tmstore/tmstore.go
- validation/flags.go
- validation/metrics.go
- validation/validators/metrics.go
Adding metrics on stores.
Clean-up package metrics.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-core/455)
> store: metrics

- Makefile
- version.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-core/456)
> ci: disable cgo for darwin

- postgresstore/postgresstore.go
- postgresstore/stmts.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-core/463)
> fix schema and table creation

- cmd/btcfossilizer/main.go
- cmd/couchstore/main.go
- cmd/dummybatchfossilizer/main.go
- cmd/dummyfossilizer/main.go
- couchstore/api.go
- couchstore/couchstore_test.go
- elasticsearchstore/cmd.go
- elasticsearchstore/elasticsearchstore_test.go
- postgresstore/cmd.go
- postgresstore/main_test.go
- rethinkstore/cmd.go
- rethinkstore/main_test.go
- rethinkstore/rethinkstore.go
- testutil/docker.go
- testutil/filetesting.go
- tmpop/tmpoptestcases/validation.go
- tmstore/tmstore.go
- util/orStrings.go
- util/orstrings_test.go
- util/retry.go
- util/retry_test.go
- util/signalcontext.go
- util/signalcontext_test.go
- validation/configloader_test.go
- validation/filewrapper_test.go
"utils" and "testutil" was a mess, "utils" contained a mix of test and non-testutilities.
Cleaned that up.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-core/465)
> utils: clean up

- batchfossilizer/batchfossilizer.go
- monitoring/errorcode/errorcode.go
- monitoring/metrics.go
- monitoring/span.go
- monitoring/store.go
- store/storehttp/storehttp.go
- tmpop/tmpop.go
- tmstore/tmstore.go
- validation/filewrapper.go
Leverage structured errors to improve spans and metrics.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-core/469)
> errors: span and metrics

- jsonhttp/jsonhttp.go
If this config option is set to true it will add the parent span as a link rather than making it the parent of the new the span.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-core/471)
> remove isPublicEndpoint flag

- fossilizer/fossilizerhttp/fossilizerhttp.go
- fossilizer/fossilizerhttp/fossilizerhttp_test.go
It should be the user's choice to add a meta field or not.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-core/475)
> fossilizer: make meta optional

- .semaphore/boilerplate
- .semaphore/docker.yml
- .semaphore/semaphore.yml
- Gopkg.lock
- Gopkg.toml
- jsonhttp/jsonhttp.go
Added Semaphore 2 file, and fixed deps, that was painful....
https://stratumn.semaphoreci.com/workflows/b404c03a-8172-4fe3-ab1c-c59ba7fdf41f
I saw we do stuff on Semaphore 1 for Docker stuff. Can someone help me with that, I'm not sure what it does.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-core/478)
> ci: add semaphore.yml and fix deps

- .semaphore/docker.yml
- Make sure only Linux binaries are built
- Make sure `make docker_images` doesn't rebuild binaries
Closes #479
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-core/480)
> ci: optimize publish to DockerHub

- .semaphore/docker.yml
- Dockerfile.tpl
- Makefile
The target builds dynamically linked binaries from within a container.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-core/483)
> ci: compile in Docker using golang 1.11.2

- validation/validators/participants.go
- validation/validators/participants_test.go
This one is simpler: a vote link should contain a valid signature and have an `update` parent.
I also added metrics error reporting.
Everything is ready for the final brick, updating the `accepted` link once enough votes have been gathered (in the next PR).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-core/488)
> validation: validate participant update vote

- validation/validators/governance.go
- validation/validators/governance_test.go
Bootstrap the validator that checks updates to a process' validation rules.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-core/492)
> validation: bootstrap governance validator

- Gopkg.lock
- Gopkg.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-core/493)
> deps: update chainscript

- fossilizer/README.md
- store/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-core/504)
> documentation: fossilizer and store

- CHANGE_LOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-core/513)
> release: 0.3.1

- batchfossilizer/batchfossilizer.go
💣
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-core/518)
> fix batch fossilizer provider

- batchfossilizer/batchfossilizer.go
- batchfossilizer/batchfossilizer_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-core/519)
> Fix duplicate fossil in batchfossilizer

- blockchain/btc/btctimestamper/btctimestamper.go
- blockchain/btc/btctimestamper/btctimestamper_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-core/522)
> Handle compressed keys in TimestampHash

- Gopkg.lock
- Gopkg.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-core/524)
> upgrade go-chainscript

- CHANGE_LOG.md
- blockchain/btc/blockcypher/blockcypher.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-core/526)
> ENG-184: Fix fossilizer UTXO selection

- blockchain/btc/btctimestamper/btctimestamper.go
These things are so annoying to test...
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-core/527)
> ENG-184: Take only one utxo
