stratumn/go-core

- cli/cli.go
- cli/test.go
Tests often need to run a command to clean up (like `docker-compose down`)
after the tests run, even after if the tests fail. Currently it is
possible, but it is tedious to return the tests exit code properly.
This commit makes `strat test` execute a `down:test` script if present
after the tests. It will handle the exit code properly.
> Add support for `strat` `down:test` script

- cli/build.go
- cli/cli.go
- cli/generate.go
- cli/run.go
- cli/test.go
- cli/up.go
This change makes it possible to pass arguments (both flags and
parameters) to a script when executing it.
For instance, you might do something like:
```
$ strat run script compose:dev ps -q
```
Both `ps` and `-q` will be appended to the script command.
However, due to flag parsing, if executing a builtin command, you have
to seperate script flags if there are no extra parameters provided.
For instance:
```
$ strat run up -d
```
will not work because `strat` will try to parse the flag. You can work
around this issue by doing instead:
```
$ strat run up -- -d
```
> Allow `strat` scripts to accept extra arguments

- cli/generate.go
- cli/generators.go
- cli/update.go
- cmd/strat/doc.go
- generator/repo/repo.go
- generator/repo/repo_test.go
- vendor/golang.org/x/oauth2/AUTHORS
- vendor/golang.org/x/oauth2/CONTRIBUTING.md
- vendor/golang.org/x/oauth2/CONTRIBUTORS
- vendor/golang.org/x/oauth2/LICENSE
- vendor/golang.org/x/oauth2/README.md
- vendor/golang.org/x/oauth2/client_appengine.go
- vendor/golang.org/x/oauth2/internal/oauth2.go
- vendor/golang.org/x/oauth2/internal/token.go
- vendor/golang.org/x/oauth2/internal/transport.go
- vendor/golang.org/x/oauth2/oauth2.go
- vendor/golang.org/x/oauth2/token.go
- vendor/golang.org/x/oauth2/transport.go
- vendor/vendor.json
This change makes it possible to access private Github repositories
using a Github OAuth2 token.
The token can be specified via environment variable `GITHUB_TOKEN` or
via a flag `-ghtoken` on commands that support it.
> Make `strat` support private Github repositories

- cli/cli.go
- cli/update.go
This change should fix `strat update` not working when the temporary
directory is on a different file system.
Resolves #70.
> Fix `strat update` not working in some cases

- cli/cli.go
- cli/deploy.go
- cmd/strat/doc.go
- cmd/strat/main.go
The command expects an environment name as the first argument. It will
try to execute the `deploy:{env}` script of the project.
> Add `strat deploy` command

- cli/build.go
- cli/cli.go
- cli/deploy.go
- cli/down.go
- cli/generate.go
- cli/pull.go
- cli/push.go
- cli/run.go
- cli/test.go
- cli/up.go
This change adds a `-stdin` flag to all `strat` commands that execute
scripts. It is set to `false` by default. If true, the standard input will be
attached to the process executing the shell command.
> Add `-stdin` flag to script runners

- generator/generator.go
Expose a function to generators that allows them to read environment variables.
Resolves #94.
> generator: add getenv function

- cmd/tmstore/doc.go
- cmd/tmstore/main.go
- tmstore/tmclient.go
- tmstore/tmstore.go
- tmstore/tmstore_test.go
- utils/retry.go
- utils/retry_test.go
- didSaveChans must be notified when a new Block is received by the
underlying Tendermint Application
- it cannot be done in the SaveSegment method (called only by the
transaction maker) but it must leverage the Tendermint Core websocket endpoint
> Fix didSaveChans notification in TMStore

- strat/cmd/cmd.go
- strat/cmd/update.go
- tmpop/query.go
- tmpop/tmpop.go
- tmpop/tmpop_test.go
- tmstore/tmstore.go
* tmstore/tmpop: Minor cleanup (changing strings to constants, etc...)
* tmpop(breaking): tmstore uses binary for the link hash instead of strings
* fix lint errors
> minor cleanup (has breaking change)

- cs/cs.go
- cs/cs_test.go
- dummystore/dummystore.go
- filestore/filestore.go
Update `dummystore` and `filestore` so they no longer need the `ContainsString()` method.
> cs: add `Link.GetTagMap()`

- Makefile
It prevents Stack Traces from showing the developer local $GOPATH
- Before:
```
panic: BLAH
goroutine 1 [running]:
main.main()
/Users/adrien/workspace/go/src/github.com/stratumn/sdk/cmd/filetmpop/main.go:27
+0x64
```
- After:
```
panic: BLAH
goroutine 1 [running]:
main.main()
src/github.com/stratumn/sdk/cmd/filetmpop/main.go:27
+0x64
```
> Trim local $GOPATH from generated binaries

- .travis.yml
Makes Travis install `golint` and run `make lint` after the tests.
> travis: run make lint

- .travis.yml
- cmd/dummyfossilizer/doc.go
- cmd/dummyfossilizer/main.go
- cmd/dummystore/doc.go
- cmd/dummystore/main.go
- cmd/filestore/doc.go
- cmd/filestore/main.go
- cmd/tmstore/doc.go
- cmd/tmstore/main.go
- dummyfossilizer/dummyfossilizer.go
- dummystore/dummystore.go
- filestore/filestore.go
- fossilizer/fossilizerhttp/example_test.go
- fossilizer/fossilizerhttp/fossilizerhttp.go
- fossilizer/fossilizerhttp/fossilizerhttp_test.go
- fossilizer/fossilizerhttp/util_test.go
- jsonhttp/jsonhttp.go
- jsonws/basic.go
- store/storehttp/cmd.go
- store/storehttp/example_test.go
- store/storehttp/storehttp.go
- store/storehttp/storehttp_test.go
- store/storehttp/util_test.go
* in most packages, routines will not return until child goroutines are finished
* cleaner fossilizerhttp server
* also using the go1.8 http.server.Shutdown() method to cleanly shutdown servers
> code quality: predictable goroutines

- cmd/filetmpop/main.go
- tmpop/cmd.go
The current `tmpop.Run` function was a legacy from when we only launched the ABCI app independently.
Code from the cmd module has been moved to it so that it's reusable for each adapter.
> Make tmpop run function reusable

- RELEASE_NOTES.md
- strat/cmd/update.go
`strat update` will now update both the CLI and generators.
In the future it would be nice to disable this feature if installed
via homebrew and recommend using `brew update && brew upgrade`
instead.
Closes #110.
> strat: change update mechanism

- store/storehttp/storehttp.go
- tmpop/testdata/rules.json
- tmpop/tmpop.go
- tmpop/tmpop_test.go
- tmstore/testdata/rules.json
- tmstore/tmstore.go
- tmstore/tmstore_test.go
- tmstore/util_test.go
- validator/root.go
- validator/schema.go
The goal is to have agent-ui display the validation error properly.
The solution is not ideal. It could be improved by moving ErrHttp out
of the jsonhttp package and create a more generic error package with
HTTP status awareness.
> validation: return bad request on validation error

- Makefile
- strat/cmd/cmd.go
This commit makes the Makefile override the default generator branch
used by strat. It uses the version tag as the name of the branch.
Closes #161.
> strat: override default generator branch

- strat/cmd/cmd.go
- strat/cmd/update.go
This commit will prevent `strat update` from updating the CLI if it
was installed via Homebrew. The behavior can be overridden using the
`--force` flag. It will still update the generators.
This is achieved by checking if a linked keg using `brew info` exists
and has the same version as the current `strat`.
Close #153.
> strat: don't update CLI if installed via Homebrew

- validator/root.go
- validator/schema.go
We don't consider it as an error not to have an action string.
It may be perfectly valid. It just ain't validatable by the
schema validator.
> validator: reduce log verbosity in validations

- tendermint/cmd.go
Else fallback to $HOME/.tendermint.
This behaviour should be more consistent with tendermint cli.
> tendermint: use TMHOME value if present

- .travis.yml
- Makefile
Build a docker image tagged with the commit hash (eg: `stratumn/filetmpop:32fe9d75`) after each successful build on master.
We could chose to push after each successful build on all branches. We'd just have to add:
```
all_branches: true
```
to the `on:` conditions
What do you think?
> ci: build and push docker image

- store/storehttp/storehttp.go
- store/storehttp/storehttp_test.go
- store/storehttp/util.go
Slices in query parameters must now use the empty brackets convention.
For example:
GET /segments?mapIds[]=id1&mapIds[]=id2&tags[]=t1&tags[]=t2
It works whether the brackets are URL-encoded or not.
This is a breaking change, the old format is no longer supported.
> storehttp: use brackets for query string slices

- strat/cmd/build.go
- strat/cmd/cmd.go
- strat/cmd/deploy.go
- strat/cmd/down.go
- strat/cmd/generate.go
- strat/cmd/pull.go
- strat/cmd/push.go
- strat/cmd/root.go
- strat/cmd/run.go
- strat/cmd/test.go
- strat/cmd/up.go
Instead of using the `exec` package, running a script now calls
`syscall.exec` to execute the shell command. The difference is that
instead of launching a child process, the current process is replaced by
the shell process.
Running `strat up` still sometimes exits with a status of 2, but when a
script command fails, as a result of this change the `strat` usage message won't be
displayed. This is the expected behavior because a shell error is not a
usage error.
> strat: improve script execution

- generator/repo/repo_test.go
Makes the `generator/repo` tests always run against the `sdk-test` branch of the `generators` repo, so tests don't break when the generators' `master` branch is updated.
> generator/repo: set git branch for tests

- Gopkg.lock
- Gopkg.toml
Awaited fixes:
- rpc: fixed client WebSocket timeout
- rpc: client now resubscribes on reconnection
- fix our tmstore unit tests crashing randomly on wal file writes
> tendermint: upgrade to version 0.11.1

- strat/cmd/cmd.go
- strat/cmd/test.go
I merged too quickly yesterday... I think it's time to write tests for `strat` :)
I had forgotten to set the working dir before launching the shell command, so `strat generate` would fail when trying to execute the `init` script of a project. 
Also since now the process is completely replaced by the shell script, it is impossible to call `runScript` more than once. The `strat test` command was calling two scripts (test and down:test). Now it will only call the `test` script, so we are going to have to figure out a way to do everything with a single test command in the generators.
> strat: fix working dir and remove `test:down` script

- version.sh
New way is a bit simpler. We also want to prevent "No names found,
cannot describe anything" errors in travis logs.
> *: improve version computation from git

- generator/generator.go
- generator/generator_test.go
- generator/testdata/filename_subst/files/file-XXX.json
For multi-process we generate one action file per-process via a file-substitution feature.
Unfortunately the file created doesn't receive the substitution information, so it doesn't know which process it's representing.
This PR forwards the substitution info to the template so that it can customize the file for the process it implements (will be useful for the generator changes I'll need to dynamic process loading).
> generator: supply substitution info to processed file

- jsonws/jsonwstesting/mockconn_test.go
Using %d for time.Time is not allowed in go tip
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/sdk/227)
> jsonwstesting: fix bad string format

- .travis.yml
CGO has to be explicitly disabled for our binaries to run on our docker images
that are "FROM scratch"
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/sdk/228)
> ci: fix binary building for docker

- store/store.go
- store/store_test.go
- store/storetestcases/findsegments.go
- store/storetestcases/storetestcases.go
The segment match method now compares the segments linkHash to
the linkHashes slice in the segmentFilter if it is present to
determine a match.
I think this should be good to go I added some tests for the relevant parts. I was expecting to have to make more changes to get the add tests in `storetestcases/findsegments.go` to work, but I did not need to change anything more. 
#216
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/sdk/231)
> store: add linkHashes matching to segment match method

- store/storetestcases/findsegments.go
#230 was not compatible with #231 since the pagination limit must be specified in the segment filter from now on.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/sdk/233)
> storetestcases: fix find tests without pagination limit

- couchstore/couchstore.go
Removed validation from couchstore as it is already done at storehttp level.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/sdk/238)
> couchstore: remove segment validation

- .travis.yml
- couchstore/couchstore_test.go
This is a temporary solution until we launch a couchdb instance from couchstore TestMain rather than within Travis.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/sdk/240)
> couchstore: add integration flag for tests

- store/store.go
Define the new interfaces we want to migrate to.
We will then migrate our existing stores one by one, and when all are migrated we'll remove the old interfaces and remove the "V2" in some interface names.
In the next pull requests I'll prepare today to setup that work, I'll:
* Update storetestcases to test stores through these new interfaces when they support it
* Migrate FileStore to the new interfaces to see if it hits some issues
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/sdk/239)
> stores: define new store interfaces

- couchstore/couchstore_test.go
initAdapter in storetestcases already logs in any error that might
happen during initialization.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/sdk/243)
> couchstore: clean adapter init in test

- cs/cs.go
- cs/cs_test.go
- cs/cstesting/cstesting.go
- filestore/batch.go
- filestore/filestore.go
- store/store.go
- tmpop/tmpoptestcases/transaction.go
Doing the migration on FileStore helped me find the pain points that we'll experience on stores.
I think we need to get rid of the Segment.Meta.Data map right now (it's useless to write code to support that in the new methods since we want to remove it anyway) -> I removed tests on that feature.
We need to do a bit of MergeMeta magic in the implementation of AddEvidence which will probably end up somewhat duplicated in all stores during the migration, but since we'll remove this and get rid of the "pending" state after the migration I think it's ok for now.
I didn't do the implementation of BatchV2 right now: I think that BatchV2 will be much simpler than Batch(V1) since the only operation will be "createLink" so we can update bufferedbatch at the end of the migration to directly …
> filestore: update to new store interface

- filestore/batch.go
- filestore/filestore.go
- leveldbstore/leveldbstore.go
- leveldbstore/leveldbstore_test.go
This store is the first implementation of the KeyValueStore interface (and we probably won't need another implementation, except if we want a replicated KeyValueStore later).
The idea is to use this store in most other stores that want to support key-value operations.
FileStore will now use this store instead of directly using the Tendermint level DB.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/sdk/249)
> leveldbstore: create a dedicated key-value store.

- dummystore/batch.go
- dummystore/dummystore.go
- dummystore/dummystore_test.go
- store/store.go
This one was pretty simple.
Migrate the dummy store to implement the new store interface and run both test suites.
I think that after that, it's time to migrate the "big stores" (like postgres, couch and rethink). The initial implementers of these stores will most likely do it a lot faster than me, so if I could get help on that it would be perfect !
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/sdk/251)
> dummystore: migrate to new interface

- bufferedbatch/batchV2.go
- bufferedbatch/batchV2_test.go
- cs/cs.go
- store/store.go
- store/store_test.go
- store/storetesting/mock_batch.go
- store/storetesting/mockadapter.go
Implement a batch v2 buffered batch.
It will most likely be used as-is in all our stores since the batch is now simpler than what it was previously.
Note: I found it horrible to have to manually implement the mocks, we need to take some time to find a good package to do that for us (and at the same time add a good assertions library for our unit tests).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/sdk/258)
> bufferedbatch: batch v2 implementation

- validator/root.go
- validator/schema.go
- validator/validator.go
- validator/validator_test.go
We currently don't provide a hash of the validations file used.
This is useful for the changes we want to do on TMPoP, where the validations hash will be part of the AppHash.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/sdk/260)
> validator: provide a validations hash

- validator/root.go
- validator/schema.go
- validator/validator.go
During the store migration, we'll need both a Validate and ValidateLink function.
Once the store migration is complete, we can update the Validate function to operate on Links instead of segments.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/sdk/265)
> validation: temporarily add ValidateLink

- store/storetestcases/storetestcases.go
This fixes a SIGSEGV in the benchmark tests (`types.NewBytes32FromString` returned `nil` and an `error` which was swallowed, hence causing a SIGSEGV when trying to convert to string)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/sdk/267)
> storetestcases: fix malformed bytes32 test string

- .travis.yml
Closes #269 
`dep ensure` takes about 10s now (used to take about 40s)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/sdk/272)
> ci: cache vendor directory

- .travis.yml
The Makefile uses the DOCKER_USER variable to select the repository
where images should be pushed. We uses to use this variable to define
the user of Docker Hub that can push images.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/sdk/278)
> ci: fix docker repository

- cs/evidences/evidences.go
- store/store.go
- tmpop/tmpop.go
- tmpop/tmpoptestcases/lastblock.go
- tmpop/tmpoptestcases/query.go
- types/types.go
- types/types_test.go
This helps readability.
I also think that most helper methods on Bytes32 should explicitly handle the nil types so that we don't get an ugly seg fault when we call them on a nil pointer.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/sdk/277)
> types: add Equals utilities to Bytes32

- bufferedbatch/batch.go
- bufferedbatch/batch_test.go
- cs/cs.go
- cs/cs_test.go
- cs/cstesting/cstesting.go
- cs/util_test.go
- store/store_test.go
- store/storehttp/storehttp.go
- store/storehttp/storehttp_test.go
- store/storetestcases/createlink.go
- store/storetestcases/findsegments.go
- store/storetestcases/getsegment.go
- store/storetesting/mockadapter_test.go
- tmpop/state.go
At last, we can clean up many operations that conceptually acted on Links but were defined on Segment.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/sdk/285)
> cs: move validate and other utility methods from segment to link

- tmpop/events.go
- tmpop/query.go
- tmpop/tmClient.go
- tmpop/tmpop.go
- tmpop/tmpoptestcases/evidence.go
- tmpop/tmpoptestcases/mocks/mock_tmclient.go
- tmpop/tmpoptestcases/query.go
- tmpop/tmpoptestcases/transaction.go
- tmstore/tmstore.go
The FireEvent method on Tendermint Client was in fact not meant to be used by the ABCI.
After discussing this with the Tendermint team, an ok solution is to store pending events in tmpop and deliver them through an abci query.
Tendermint will maybe support ways for us to notify connected clients directly in the future, but meanwhile this is a good solution (even though I don't find it very elegant).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/sdk/291)
> tmpop: deliver events via abci query

- Gopkg.lock
- Gopkg.toml
- agent/agent.go
- agent/agenttestcases/agenttestcases.go
- agent/agenttestcases/createlink.go
- agent/agenttestcases/createmap.go
- agent/agenttestcases/findsegments.go
- agent/agenttestcases/getinfo.go
- agent/agenttestcases/getmapids.go
- agent/agenttestcases/getprocess.go
- agent/agenttestcases/getprocesses.go
- agent/agenttestcases/getsegment.go
- agent/client/client.go
- agent/client/client_test.go
- agent/client/utils_test.go
- agent/plugin.go
- agent/process.go
- store/store.go
This is the second part of the agent-client (there are three in total).
It contains mainly two things : 
- a mock for the agent and its http server (I had to add an extra dependency to gorilla/mux for the router, because the one we are using in `storehttp` [does not support the agent's routes](https://github.com/julienschmidt/httprouter/issues/12))
- the testing package layout for the agent-client, It lives in its own sub-package because I felt it could be somehow shared with the agent tests but I did not figure out how exactly (I'm open to suggestions here)
Next PR will be actual implementation !
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/sdk/297)
> agent-client-go: test cases and mock agent

- .travis.yml
- Gopkg.lock
- Gopkg.toml
- cmd/tmstore/main.go
- cs/evidence_test.go
- cs/evidences/evidences.go
- tendermint/cmd.go
- tmpop/data.go
- tmpop/error.go
- tmpop/state.go
- tmpop/tmClient.go
- tmpop/tmpop.go
- tmpop/tmpoptestcases/evidence.go
- tmpop/tmpoptestcases/query.go
- tmpop/tmpoptestcases/tmpoptestcases.go
- tmpop/tmpoptestcases/transaction.go
- tmpop/transaction.go
- tmstore/tmstore.go
- tmstore/tmstore_test.go
- tmstore/util_test.go
Update to Tendermint 0.13.0 (0.14.0 is advertised as release but in fact it requires a commit from tmlibs' develop branch, so it's not really ready for release yet).
There was a big types change where Tendermint removed a lot of their types and forces us to have different return types per ABCI operation. I think it's overall a good change, our internal types in TMPoP were too tightly coupled with Tendermint's types, so I introduced an ABCIError type inside TMPoP.
Socket management / events changed a lot and isn't well documented, I had to dig through Tendermint's code to get it to work.
I want to do an end-to-end test with multiple nodes before committing this change, I'll be working on that today and will report the results on this PR.
---
This change is [<img …
> tendermint: update to 0.13.0

- Gopkg.lock
- cmd/couchstore/main.go
- couchstore/api.go
- couchstore/couchstore.go
- couchstore retries connecting to couchdb only if couchdb is unavailable not for other errors
- couchstore creates _users and _replicator required dbs in couchdb if they don't already exist
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/sdk/320)
> couchstore: retry only if couchdb unavailable and create system dbs

- generator/generator.go
- generator/input.go
Allow generator template to use ints.
Provide a loop function for generator templates.
This will be used by the generators to provide a 'generate cluster' option to create a Tendermint cluster for E2E testing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/sdk/319)
> strat: more generator options

- agent/agent.go
- agent/agenttestcases/actions.js
- agent/agenttestcases/agenttestcases.go
- agent/agenttestcases/getinfo.go
- agent/agenttestcases/uploadprocess.go
- agent/client/client.go
- agent/client/utils_test.go
- agent/mock.go
Agent client can now upload a process to the agent. When launching integration tests for agent/client spin up an agent with no processes and a store. The action.js file will be used to create the test process.
I've removed the plugins as the process is launched with no plugins.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/sdk/322)
> agent/client: add uploadprocess endpoint

- batchfossilizer/batchfossilizer.go
It's useful to keep the transformer when stopping/restarting a fossilizer
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/sdk/328)
> batchfossilizer: stop does not reset transformer

- postgresstore/stmts.go
This commit changes the way map ids are ordered by the postgresstore. I didn't add any test since this behavior isn't specified by the store interface, and other stores may sort segments and map ids in a different manner.
I created a card (#333) to add a `Sort` object to customize the sorting method used in `FindSegments` and `GetMapIds`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/sdk/334)
> postgresstore: sort mapIds by last update

- Gopkg.lock
- Gopkg.toml
- cs/cs.go
- cs/cs_test.go
- cs/cstesting/cstesting.go
- cs/signature.go
- cs/signature_test.go
- tmpop/state.go
- validator/baseconfig.go
- validator/baseconfig_test.go
- validator/configloader.go
- validator/configloader_test.go
- validator/multivalidator.go
- validator/multivalidator_test.go
- validator/schema.go
- validator/schema_test.go
- validator/signature.go
- validator/signature_test.go
- link format is evolving : there is a new `Signatures` field 
```golang
type Link struct {
State      map[string]interface{} `json:"state"`
Meta       map[string]interface{} `json:"meta"`
Signatures []*Signature           `json:"signatures"`
}
```
- a new boolean `signatures` can be added in in the validators : 
```json
"myprocess": [{
"type": "init",
"signatures": true,
"schema": {...}
}, {
"type": "someAction",
"signatures": true
}]
```
If this boolean is set to true, signatures present in the link will be verified. If it's omitted, signatures won't be checked. This parameter may be used independently from the `schema` one.
NEXT PR : actual verification of signatures using the `go-jmespath` package to determine the payload and the `ed25519` signature algorithm.
---
This change is [<img …
> validator, cs: add signature type and signature validator

- validator/signature.go
- validator/signature/ecdsa.go
- validator/signature/rsa.go
- validator/signature/schemes.go
- validator/signature/schemes_test.go
- validator/signature_test.go
I factorized signature validation so it's trace compatible.
Handled signature schemes are now ed25519, ecdsa256 and RSA.
I'll update trace-api once it is merged with master.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/sdk/337)
> validator: factorize signature verification, add ECDSA & RSA

- cs/cstesting/cstesting.go
- tmpop/tmpop.go
- tmpop/tmpoptestcases/validation.go
- tmstore/testdata/rules.json
- tmstore/tmstore_test.go
- validator/baseconfig.go
- validator/baseconfig_test.go
- validator/configloader.go
- validator/configloader_test.go
- validator/multivalidator.go
- validator/multivalidator_test.go
- validator/pki.go
- validator/pki_test.go
- validator/schema.go
- validator/schema_test.go
- validator/signature.go
- validator/signature_test.go
- validator/validator.go
- validator/validator_test.go
`rules.json` format was updated:
- a `pki` property must be specified: it defines a list of "identities" linked to public keys. It allows signature validation rules to be more user-friendly (one can require signatures by name, role or public key)
- an identifier `id` must be specified in a validator
- the `signatures` property of a validator is now a slice of strings. In the example below, the `init` action of the `testProcess` process (the first segment) needs to be signed by both `TESTKEY1` (alice) and `TESTKEY2` (bob). If this property is omitted or empty, no signature is required. Nevertheless, it there are signatures in `link.Signatures`, they will still be verified and an error will be thrown if an error is encountered.
```json
{
"pki": {
"TESTKEY1": {
"name": "Alice Van den …
```
> validator: check signatures against PKI

- .vscode/launch.json
- Gopkg.lock
- tmpop/state.go
- tmpop/tmpop.go
- tmstore/testdata/rules.new.json
- tmstore/tmstore_test.go
This PR avoids reading the validator rules file at each begin block. There is a file watcher on file which reloads validators
The library fsnotify is used and will be removed in a next PR prefering reading data from segments.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-indigocore/345)
> Load validator rules asynchronously

- Makefile
- utils/docker.go
Authorize pull image failure when running docker container
Avoid tests with cache
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-indigocore/351)
> CI improvements

- Gopkg.lock
- Gopkg.toml
- cs/evidence_test.go
- tendermint/cmd.go
- tmpop/tmClient.go
- tmpop/tmpop.go
- tmpop/tmpoptestcases/evidence.go
- tmpop/tmpoptestcases/tmpoptestcases.go
- tmpop/tmpoptestcases/transaction.go
- tmstore/tmstore.go
- tmstore/tmstore_test.go
- `Commit()` return value does not have `Code` and `Log` anymore : we have to return an empty `ResponseCommit` if an error occurred.
- Subscribing twice to a tendermint event (ie: NewBlock event) causes an error. Also, unsubscribing  when there is no current subscription causes an error.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-indigocore/350)
> tendermint: upgrade to 0.16.0

- batchfossilizer/batchfossilizer.go
- batchfossilizer/batchfossilizer_test.go
After viewing the last JustForFunc episode, I tried to detect race condition in go-indigocore using `go test -race`.
This fix concerns batchfossilizer.
There are potential race conditions detected in `MockConn` (painful to fix) and in tendermint, so I have not generalized the race option when launching tests.
[Youtube: JustForFunc #29](https://www.youtube.com/watch?v=ifBUfIb7kdo&feature=em-subs_digest)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-indigocore/353)
> batchfossilizer: fix race condition

- validator/configloader.go
- validator/configloader_test.go
- validator/multivalidator_test.go
- validator/pki.go
- validator/pki_test.go
- validator/schema.go
- validator/schema_test.go
- validator/transition.go
- validator/transition_test.go
- validator/util_test.go
Implementation of SRP4.
Validation of transitions.
Here is a rule example:
```
{
"auction": {
"pki": {},
"types": {
"initState": {
"transitions": {
"initialize" : [""]
}
},
"OrderOnMarket": {
"transitions": {
"sendOrder" : ["initState", "OrderOnMarket"]
}
},
"OrderCanceled": {
"transitions": {
"cancel" : ["initState", "OrderOnMarket"]
}
}
}
}
}
```
A chainscript type is the state.
Each state has a list of possible transitions defined as _actionName_ and the list of allowed previous states.
An empty previous state is necessary to create the first link of a map
A final state is a state which is not defined in any allowed previous state.
A next PR will come once this PR will be merged to make transition validation mandatory.
---
This change is [<img …
> validator: add transitions

- Makefile
- replaced some `grep -v` by `find -not -path <path>` (@alexppxela perf improvement)
- replace `find .` by `find *` to ignore hidden files (semaphore create a `.semaphore-cache` in the current directory, which made the tests fail)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-indigocore/359)
> Makefile: ignore hidden folders and files

- bufferedbatch/batch.go
- bufferedbatch/batch_test.go
- bufferedbatch/metrics.go
- couchstore/couchstore.go
- dummystore/dummystore.go
- elasticsearchstore/cmd.go
- elasticsearchstore/elasticsearchstore.go
- filestore/batch.go
- filestore/filestore.go
- jsonhttp/jsonhttp.go
- leveldbstore/leveldbstore.go
- monitoring/errorcode.go
- postgresstore/batch.go
- postgresstore/postgresstore.go
- postgresstore/reader.go
- postgresstore/writer.go
- rethinkstore/rethinkstore.go
- tmpop/state.go
- tmpop/tmpop.go
- tmstore/tmstore.go
Add basic tracing of the top-level methods for all stores.
Add error tagging.
Add a few metrics on bufferedbatch.
I don't know yet what metrics would make sense for each of the specific stores, I think that's something we'll add afterwards when we know what we want to monitor (SQL query time, number of rows impacted, etc).
I created issue #374 which would help our monitoring give us more insight (and the ability to alert on specific errors).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-indigocore/375)
> monitoring: add tracing to all stores

- batchfossilizer/batchfossilizer.go
- batchfossilizer/batchfossilizer_test.go
- batchfossilizer/metrics.go
- batchfossilizer/util_test.go
- bcbatchfossilizer/bcbatchfossilizer.go
- bcbatchfossilizer/bcbatchfossilizer_test.go
- bcbatchfossilizer/util_test.go
- cmd/btcfossilizer/main.go
- cmd/dummybatchfossilizer/main.go
- cmd/dummyfossilizer/main.go
- dummyfossilizer/dummyfossilizer.go
- dummyfossilizer/dummyfossilizer_test.go
- fossilizer/fossilizer.go
- fossilizer/fossilizerhttp/cmd.go
- fossilizer/fossilizerhttp/fossilizerhttp.go
- fossilizer/fossilizerhttp/metrics.go
- fossilizer/fossilizertesting/example_test.go
- fossilizer/fossilizertesting/mockadapter.go
- fossilizer/fossilizertesting/mockadapter_test.go
- monitoring/fossilizer.go
Add instrumentation to fossilizers.
Because of the async job design with channels, traces will be decorrelated, but that's still helpful.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-indigocore/378)
> monitoring: instrument fossilizers

- generator/input.go
- strat/cmd/key.go
I added an other kind of input instead of using `StringSelectOptions` biut I don't know if it's worth it...
I also tried modifying `StringSelectOptions` to a `map[interface{}]string` but it really was not convenient (good to know: `'{"some": "json"}'` cannot be unmarshalled into a go type `map[interface{}]string`)
I can still convert `x509.PublicKeyAlgorithm` to a `string` but meh...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-indigocore/381)
> Generate keys from the CLI

- Dockerfile.tpl
- Makefile
When docker creates its context to create images, it takes a while because context is built from the root project directory.
Performance:
```
before: make docker_images  65.38s user 91.98s system 34% cpu 7:34.37 total
after:  make docker_images  19.54s user 12.71s system 53% cpu 59.871 total
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-indigocore/391)
> Improve docker image generation performance

- batchfossilizer/metrics.go
- bufferedbatch/metrics.go
- tmpop/metrics.go
The latest opencensus changes removed the previous "opencensus_" prefix.
I'm taking advantage of that to properly name our views (following what looks like the best practice for prometheus views).
Thanks for catching that!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-indigocore/392)
> monitoring: update metrics name

- bufferedbatch/batch.go
- bufferedbatch/batch_test.go
Bufferedbatch's CreateLink is validating the link for no reason.
All other store don't do any validation, their only responsibility is to store links.
Validation is done beforehand (in the http server for http store or in TMPoP when receiving links via DeliverTx).
Refactored bufferedbatch tests to use assertions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-indigocore/406)
> batch: remove link validation in CreateLink

- agent/client/utils_test.go
- cs/cs.go
- cs/cs_test.go
- cs/cstesting/builder.go
- cs/util_test.go
As discussed offline, removing this feature.
When we need to reference links from other stores, we'll rethink the approach depending on the usecase.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-indigocore/409)
> cs: remove including full segment in ref

- tmpop/state.go
- validator/governance.go
- validator/governance_test.go
I added an interface to the governanceManager in order to be able to mock it and to add new implementations (apart from picking updates from a local file).
I modified the behavior of the manager to run it in a goroutine and receive updates whenever it's available.
Do you think it should live it should live in its own package ?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-indigocore/413)
> validation: add interface to GovernanceManager

- validation/broadcaster.go
- validation/broadcaster_test.go
- validation/configloader.go
- validation/configloader_test.go
- validation/localmanager.go
- validation/localmanager_test.go
- validation/networkmanager.go
- validation/networkmanager_test.go
- validation/store.go
- validation/store_test.go
- validation/validation.go
- validation/validators/multivalidator.go
- validation/validators/multivalidator_test.go
- validation/validators/validator.go
In this PR: 
- small improvement on the validators side, the list of validators is now indexed by the process name (no need to call `ShouldValidate` on all validators on the multiValidator).
- a NetworkManager implementing the `validation.Manager` interface was added.
- the subscription mechansim of the Manager has been factorized and splitted in its own file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-indigocore/415)
> add network validation manager

- cs/cstesting/builder.go
- validation/localmanager.go
- validation/localmanager_test.go
- validation/networkmanager.go
- validation/networkmanager_test.go
- validation/store.go
- validation/store_test.go
I realised I made a bad design choice by letting the validation store create a new governance link by itself : 
- first and foremost : a store creating a link doesn't make any sense.
- we need to keep the signatures attached to the governance links provided by the network, otherwise they won't be valid anymore ! (obviously -_-).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-indigocore/416)
> validation: fix validation store update

- postgresstore/reader.go
- postgresstore/stmts.go
- store/storetestcases/findsegments.go
Replace all the precompiled statements by building the query in function of the filters.
- the choice of keeping the sql query raw (in comparison with using an ORM) was made for performance.
- we use db.Query / tx.Query with an already assembled query string (instead of passing a formatting string and all placeholder values) for performance. Indeed, when we use the Query() with a single argument, we bypass the prepare --> execute --> close sequence that's done behind the scenes when pasding multiple args
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-indigocore/427)
> postgresstore: refacto FindSegments queries

- tmpop/tmpop.go
If the evidence ends up null because of an error, this will cause a nullref in the AddEvidence.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-indigocore/438)
> tmpop: skip errored evidence

- couchstore/queries.go
- elasticsearchstore/api.go
- elasticsearchstore/elasticsearchstore.go
- elasticsearchstore/elasticsearchstore_test.go
- postgresstore/stmts.go
- rethinkstore/rethinkstore.go
- store/store.go
- store/store_test.go
- store/storehttp/errors.go
- store/storehttp/storehttp_test.go
- store/storehttp/util.go
- store/storetestcases/benchutil.go
- store/storetestcases/findsegments.go
- store/storetesting/mockadapter_test.go
- tmpop/tmpoptestcases/query.go
SegmentFilter now uses chainscript.LinkHash for consistency.
Note that the APIs that use URL query parameters still expect hex strings (in a URL it makes sense to use a byte encoding, and hex is easy to reason with and visual).
A new field `WithoutParent` has been added to filter for links that don't have a parent (instead of the ugly hack of distinguishing nil and "").
Fixed most of the context.TODO() in elasticsearchstore.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-indigocore/440)
> filters: link hash should be bytes

- validation/validators/refs.go
- validation/validators/refs_test.go
Adding out degree validation in the refs validator.
For all cases where a consensus algorithm runs (Tendermint, Kayak, etc) it will be enough to validate here and any store can be used underneath (even if it doesn't have built-in support like postgresstore).
Later we will provide more configuration hooks at the store level so that we can bypass the validations done in the store (like postgresstore's outDegree tables) if it has been validated upstream (at the consensus layer).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-core/447)
> validations: validate out degree

- postgresstore/postgresstore.go
- postgresstore/stmts.go
Adding foreign keys and comments where they are necessary for postgraphile.
I tested that it seems to work fine in GraphiQL.
I also did some perf testing and under heavy load request latency can easily spike to ~1 sec when reading many segments while links are being written concurrently to the same map.
We'll need to monitor the metrics during pilot to see if we need to do some performance improvements to the SQL queries.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-core/457)
> postgres: schema update for graphQL

- types/error.go
This is a proposal to add error code and component name to our errors.
It allows metrics and spans to be tagged by these two values to improve monitoring.
It will also allow the http stores to return accurate http status codes and upstream components to make more accurate decisions when receiving errors.
Let me know what you think before I start updating the error handling in the whole codebase.
Note: I hope that Go 2 will make this struct obsolete :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-core/459)
> types: add an error struct

- postgresstore/cmd.go
- postgresstore/postgresstore.go
- postgresstore/stmts.go
Split the table in two different schemas.
Trace should do the same: its tables should be in a "trace" schema.
We can then configure roles for schema access. I think this shouldn't be done inside go-core but rather as an OPS script on the DB itself. Here is what I think we should do in such a script:
- Create a user "store" in the DB with a given password
- Create a user "trace" in the DB with a given password
- Alter store schema permissions to allow both store and trace users to access it
- Alter store_private schema permissions to allow only store user to access it
- Alter trace schema permissions to allow only trace user to access it
- Provide the right connection strings so that the store http service connects as the store user and the trace API backend connects as the trace user
Does …
> postgres: add schemas

- postgresstore/postgresstore_test.go
- postgresstore/stmts.go
Declare unique constraints directly inside the `create table` statements.
I also wanted to have prevlinkhash directly reference linkhash (to prevent inserting segments with invalid parents) but it's impossible because we allow prevlinkhash to be null.
Added a small test to prevent the error we encountered when creation failed because schema/tables were already there.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-core/466)
> postgres: small improvements

- fossilizer/fossilizerhttp/fossilizerhttp.go
- fossilizer/fossilizerhttp/fossilizerhttp_test.go
This is breaking change, when Trace updates it go-core dependency it should make a change in its client code as well (maybe use js-core?).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-core/473)
> fossilizerhttp: use JSON instead of form data

- jsonhttp/jsonhttp.go
- jsonhttp/jsonhttp_test.go
There's not reason to leverage CORS protection for our store and fossilizer APIs.
We want frontend apps to be able to directly call a store or a fossilizer if needed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-core/474)
> jsonhttp: enable cors

- fossilizer/fossilizerhttp/cmd.go
- jsonhttp/jsonhttp.go
- jsonhttp/jsonhttp_test.go
- store/storehttp/cmd.go
CORS requires options calls to be handled on all routes, so I think that the easiest way is to automatically add an OPTIONS handler on all defined routes when CORS is enabled.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-core/476)
> jsonhttp: config enable CORS

- jsonhttp/errors.go
- jsonhttp/jsonhttp_test.go
- store/storehttp/storehttp_test.go
- types/error.go
Javascript clients can leverage json-structured errors.
Since we have a good nested structure internally, it's good to serialize it properly instead of converting it to a linear string.
Golang makes it a tiny bit cumbersome but it's not too ugly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-core/477)
> jsonhttp: properly format json error response

- fossilizer/fossilizerhttp/cmd.go
- jsonws/basic.go
- store/storehttp/cmd.go
Websockets also need to enable CORS.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-core/482)
> jsonws: allow cross-origin requests

- validation/validators/governance.go
- validation/validators/participant.go
- validation/validators/participant_test.go
- validation/validators/participants.go
- validation/validators/participants_test.go
Start implementing the validators required for governance in decentralized networks.
The first element needed is a special map in the validator process to track the network's participants (because we'll need this participants' list to be able to vote for validation rules updates in next PRs).
The participants map only accepts three types of links:
- `accept`: contains the latest list of participants with their voting power. Can have only one children. This is what other maps will reference to know what participants are currently in the network and should vote.
- `update`: propose a participants list update
- `vote`: vote for a participants list update
In this PR I only implement the ability to create the first `accept` link in the map. `update`, `vote` and non-initial `accept` link …
> validation: governance participants

- couchstore/couchstore.go
- elasticsearchstore/elasticsearchstore.go
- postgresstore/segment.go
- postgresstore/stmts.go
- rethinkstore/rethinkstore.go
- store/errors.go
- store/store.go
- store/store_test.go
- store/storehttp/errors.go
- store/storehttp/storehttp_test.go
- store/storehttp/util.go
- store/storetestcases/findsegments.go
- tmstore/tmstore.go
Add a mapping table to provide a reference reverse-lookup (who references me).
Expose that lookup as a new filter in FindSegments (can also be used directly with access to the DB table).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-core/489)
> postgres: referenced by

- validation/validators/governed.go
- validation/validators/governed_test.go
Bootstrap the segment validator that will be used to validate "normal" process segments in p2p decentralized networks.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-core/491)
> validation: bootstrap governed process validator

- .semaphore/semaphore.yml
- batchfossilizer/cmd.go
- cloud/aws/cmd.go
- cloud/aws/doc.go
- cloud/aws/queue.go
- cloud/aws/queue_test.go
- cloud/aws/session.go
- cloud/doc.go
- cmd/btcfossilizer/main.go
- cmd/btcfossilizer/queue.go
- fossilizer/fossilizer.go
FossilsQueue leveraging AWS SQS.
Add command-line arguments to setup AWS queue for the BTC fossilizer.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-core/498)
> fossilizer: aws queue

- blockchain/btc/blockcypher/blockcypher.go
- blockchain/btc/blockcypher/metrics.go
We can then easily alert on that metric when the fossilizer's balance is getting low.
It will prevent us from being unable to fossilize important data (we'll need to send more btc to the fossilizer address which isn't automated yet though).
Resolves #500 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-core/501)
> btc: add metric that reports account balance

- cloud/aws/session.go
Because configuring it manually just makes everything break when running inside AWS :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-core/502)
> aws: let sdk fetch credentials automagically

- monitoring/span.go
It makes it a bit more handy than using traces for quick & dirty error analysis.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-core/503)
> monitoring: add a standard error log

- batchfossilizer/batchfossilizer.go
- batchfossilizer/batchfossilizer_test.go
- fossilizer/dummyqueue/queue.go
In case fossilization failed (because of the blockcypher API for example) we push the fossils back to the queue.
This way they will be fossilized at the next batch.
We'll need to watch the queue size though in case a real issue happens (it's easy to setup an alert for that in AWS).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-core/506)
> batchfossilizer: push failed fossils back to the queue (fixes #505).

- Gopkg.lock
- Gopkg.toml
I was having issues finding my metrics tags, and I remembered that there was a bug in the Go agent.
I asked the Elastic guys to fix it (a couple of weeks ago) and they did, but it's not included in a release yet, so we need to depend on master to get metrics properly working with all tags, histograms, etc.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-core/510)
> elastic: update go agent

- postgresstore/cmd.go
It could leak the username/password.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-core/511)
> postgresstore: remove postgres URL from help output

- CHANGE_LOG.md
- postgresstore/batch.go
- postgresstore/benchmark_test.go
- postgresstore/postgresstore.go
- postgresstore/postgresstore_test.go
- postgresstore/segment.go
- store/API.md
- store/errors.go
- store/storehttp/storehttp.go
- store/storehttp/storehttp_test.go
- store/storetestcases/batch.go
- store/storetesting/mockadapter.go
Add the option to create multiple links in an atomic batch.
I chose to make it explicit that it's a batch by using a new route (it makes it easier for backwards-compatibility too). It's not unrealistic at some point to use the `/links` route and make it accept a more complex payload (collection of links + a boolean to choose what to do in case of error: atomic or not).
Fixes #515
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-core/516)
> store: create links batch

- CHANGE_LOG.md
- RELEASE_NOTES.md
- postgresstore/evidence.go
- postgresstore/segment.go
- postgresstore/stmts.go
- store/storetestcases/evidencestore.go
Encoding link and evidence data as JSON instead of protobuf.
This enables JSON field indexing in postgres which can be nice.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-core/517)
> postgresstore: link json encoding

- blockchain/btc/blockcypher/blockcypher.go
- blockchain/btc/btc.go
- blockchain/btc/btctimestamper/btctimestamper.go
- blockchain/btc/btctimestamper/btctimestamper_test.go
I couldn't find a proper solution to the issue so I used a quickfix instead.
The issue is described in detail with the fix.
The drawback to this solution is that UTXOs that are lower than the transaction fee (15000 satoshis) will never be used by the fossilizer, and we'll have to manually "merge" them from time to time (create a transaction from some wallet with all the low UTXO as inputs and only one UTXO as output, to the same address).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stratumn/go-core/525)
> Fix fossilizer issue where utxo inputs are lower than transaction fee
